### PR TITLE
Things we are fixing in every project

### PR DESCRIPTION
**Pull request by cap10morgan**
Just some more updates for things we're fixing / updating in every project as we go.

The only potentially controversial change is locking down some ports in docker-compose.yml. That seemed simpler than having to look these up all the time in dev. But of course the downside is that port conflicts are more likely to happen now.

I'm happy to back that change out if it seems not worth it. Obviously I think it is worth it. :)

### CODE REVIEW

**Comment by tie-rack** [comment]
What if we pinned those ports not to their defaults (8080, 9990, 15672), but to some _kraken_ defaults which we make up for this purpose? Like.... 26000, 26001, and 26002. We're much more likely to have something running on 8080 and 15672 outside of a kraken contest.

**Comment by cap10morgan** [comment]
Sure, that'll work.

How about (in the 50,000's so we stay up in the unregisterable port range; ending in the same 4 numbers the in-container ones do for predictability):
- 55672:15672
- 58080:8080
- 59990:9990

**Comment by tie-rack** [comment]
Sure. Make that change and get this mergable and you'll get that coveted LGTM.

**Comment by cap10morgan** [comment]
@tie-rack ready

**Comment by tie-rack** [comment]
LGTM

**Pull request merged**
